In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print("Jupyter Works! My Array:", arr)

Jupyter Works! My Array: [1 2 3 4 5]


In [ ]:
#2D 
a=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",a)   # THIS IS ALSO A MATRIX

2D Array:
 [[1 2 3]
 [4 5 6]]


In [5]:
#3D ARRAY
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D Array:\n",b)


3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#D TYPE
SAK=np.array([1,2,3,4], dtype='int16')
print("Data Type of Array:", SAK.dtype)

Data Type of Array: int16


In [9]:
SAK=np.array([1,2,3,4], dtype='bool')
print("Data Type of Array:", SAK.dtype)

Data Type of Array: bool


In [11]:
#np.arrange
np.arange(1,12,2)


array([ 1,  3,  5,  7,  9, 11])

In [ ]:
#np.ones and np.zeros 
np.ones((3,4))  #3 rows and 4 columns


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))  #3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#with reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.arange(1,12,2).reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
#np.random.random
np.random.random((3,4))  #3 rows and 4 columns AND in this case the values will be random between 0 and 1 and the values isd also a float


array([[0.10662159, 0.8311029 , 0.1160232 , 0.8989863 ],
       [0.13269285, 0.66268   , 0.32837922, 0.60113582],
       [0.79738698, 0.96838299, 0.35053521, 0.78218133]])

In [21]:
#np.linspace
np.linspace(-10,10,10)  

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
#np.identity
np.identity(4)  #4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.identity(3) #3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#ARRAY ATTRIBUTES
a1=np.arange(10)
a2=np.arange(16,dtype='float').reshape(4,4)
a3=np.arange(8).reshape(2,2,2)

In [27]:
#ndim(n dimwnsions)----- THEY FIND THE NUMBER OF DIMENSIONS IN THE ARRAY
print("Number of Dimensions in a3:", a3.ndim)

Number of Dimensions in a3: 3


In [28]:
#shape-----IT SHOWS THE NUMBER OF ELEMENTS IN EACH DIMENSION OF THE ARRAY
print("Shape of a2:", a2.shape)


Shape of a2: (4, 4)


In [29]:
#size-----IT SHOWS THE TOTAL NUMBER OF ELEMENTS IN THE ARRAY
print("Size of a3:", a3.size)

Size of a3: 8


In [30]:
#itemsize-----IT SHOWS THE NUMBER OF BYTES USED BY EACH ELEMENT OF THE ARRAY
print("Item Size of a2:", a2.itemsize)

Item Size of a2: 8


In [32]:
#CHANGING DATATYPE 
#astype()-----IT CHANGES THE DATATYPE OF THE ARRAY
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [33]:
#ARRAY OPERATIONS
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [34]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#SCALER OPERATIONS

#ARITHMETIC OPERATIONS
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [37]:
a1**3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [38]:
a2+2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [39]:
#RELATIONAL OPERATIONS
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
#VECTOR OPERATIONS
#arithmetic operations

a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
#ARRAY FUNCTIONS
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[87., 93.,  0.],
       [28., 29., 51.],
       [48., 42., 63.]])

In [46]:
#MAX/MIN/SUM/PROD
np.max(a1)


np.float64(100.0)

In [47]:
np.min(a1)

np.float64(10.0)

In [48]:
np.sum(a1)

np.float64(548.0)

In [49]:
np.prod(a1)

np.float64(2451626868600000.0)

In [50]:
#0-> col and 1-> row
np.max(a1, axis=0) #this show the highest number of row in each column and the output will be a 1D array with the highest number of each column

array([ 78.,  97., 100.])

In [51]:
np.min(a1, axis=1) #this show the lowest number of column in each row and the output will be a 1D array with the lowest number of each row

array([10., 67., 47.])

In [52]:
# MEAN/MEDIAN/STANDARD DEVIATION/VARIANCE
np.mean(a1)

np.float64(60.888888888888886)

In [53]:
np.median(a1)

np.float64(67.0)

In [7]:
np.std(a1)

np.float64(27.632509034750274)

In [8]:
np.var(a1)

np.float64(763.5555555555555)

In [10]:
#TRIGONOMETRIC FUNCTIONS

np.sin(a1)
np.cos(a1)

array([[ 0.56975033,  0.3174287 ,  1.        ],
       [-0.96260587, -0.74805753,  0.7421542 ],
       [-0.64014434, -0.39998531,  0.98589658]])

In [12]:
#DOT PRODUCT
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponential functions
np.log(a1)  #natural & and IN THID CASE WE CAN FIND THE LOG OF EACH ELEMENT IN THE ARRAY AND THE OUTPUT WILL BE A 2D ARRAY WITH THE LOG OF EACH ELEMENT


C:\Users\Saksham\AppData\Local\Temp\ipykernel_4592\2187921928.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)  #natural log and IN THID CASE WE CAN FIND THE LOG OF EACH ELEMENT IN THE ARRAY AND THE OUTPUT WILL BE A 2D ARRAY WITH THE LOG OF EACH ELEMENT


array([[4.46590812, 4.53259949,       -inf],
       [3.33220451, 3.36729583, 3.93182563],
       [3.87120101, 3.73766962, 4.14313473]])

In [16]:
#ROUND/FLOOR/CEIL
np.round(np.random.random((3,3))*100)  #this will round the values of the array to the nearest integer


array([[53., 93., 60.],
       [62., 40., 38.],
       [20., 99., 63.]])

In [17]:
np.floor(np.random.random((3,3))*100)  #they have convert into a back of the integer value


array([[53., 56.,  5.],
       [23., 45., 31.],
       [48., 45., 73.]])

In [4]:
#INDEXING AND SLICING

a1=np.arange(10)
a2=np.arange(16).reshape(4,4)
a3=np.arange(8).reshape(2,2,2)


In [19]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#INDEXING
a1[-1]  #this will give the last element of the array

np.int64(9)

In [22]:
a1[1]  #this will give the second element of the array

np.int64(1)

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
a2[1,2]  #this will give the element in the second row and third column of the array

np.int64(6)

In [25]:
a2[3,1]  #this will give the element in the fourth row and second column of the array

np.int64(13)

In [26]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
a3[1,0,0]  #this will give the element in the second block, first row and first column of the array

np.int64(4)

In [28]:
a3[0,1,1]  #this will give the element in the first block, second row and second column of the array

np.int64(3)

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
#if we have output([[5,6],[9,10]]) then we can get the output by using the following code
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [10]:
a2[0::3,0::2] #this will give the elements in the first and third row and first and third column of the array

array([[ 0,  2],
       [12, 14]])

In [11]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
#if we have output([4,7]) then we can get the output by using the following code
a2[1,0::3]

array([4, 7])

In [19]:
#([[1,  2,  3],[5,  6,  7]])
a2[0:2,1:]
       

array([[1, 2, 3],
       [5, 6, 7]])